name: lp
channels:
  - conda-forge
dependencies:
  - git
  - pip
  - make
  - re2c
  - toml
  - pytest
  - jupyter
  - xeus=5.1.0
  - xeus-zmq=3.0.0
  - nlohmann_json=3.11.3
  - jupyter_kernel_test
  - xonsh=0.16.0
  - zlib
  - cmake
  - numpy
  - flake8
  - setuptools
  - bison=3.4
  - python=3.10.2
  - llvmdev=11.0.1
  - zstd-static=1.5.5
